version: '3'

services:
    app:
        container_name: lb_server
        restart: always
        build:
            context: .
            dockerfile: nginx.dockerfile
        ports:
            - 80:80